### ISSUE TITLE
Problems with jasmine.json support 

### ISSUE THREAD

**Issue by xnnkmd** [svi3c/jasmine-ts#12]
I am trying to use a jasmine.json file for configuration like the one below:
Unfortunately, spec files are not picked up (only works if I specify them on the command line as in this npm's example). Also, not all helper files are loaded. I have both a "typings.ts" and a "config.ts" file in the helpers dir refered to by the jasmine.json file below but only the "config.ts" is picked up.

```
{
  "spec_dir": "src/spec",
  "spec_files": [
    "**/*[sS]pec.ts"
  ],
  "helpers": [
    "support/*.ts"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}

```

**Comment by xnnkmd** [comment]
Maybe I should add that the most importan issue here is that not all helpers files are loaded. This causes compilation errors for me.

**Comment by xnnkmd** [comment]
Found out some more. It seems that the spelling of the filenames are important (file order). If I add the following helper files to jasmine-ts I get compilation errors in config.ts about missing things from typings.ts:

config.ts
typings.ts

But if I rename typings.ts to _typings.ts, it is loaded before config.ts and everything works..... The file order does not matter with tsc but with jasmine-ts it does ?

**Comment by bondarukoleh** [comment]
@xnnkmd Thank you, man. Spent a few hours trying to make it work, until decided to check out issues.

**Comment by ert78gb** [comment]
from 0.3.2 you can use the `--config` parameter to pass the jasmine config file.
I close this issue, but feel free to reopen if something missing
