### ISSUE TITLE
Support for node.js CLI arguments like ts-node has

### ISSUE THREAD

**Issue by xnnkmd** [svi3c/jasmine-ts#13]
I would like to specify some of nodes command line arguments for jasmine-ts (in particular the -r for requiring extra files). Ts-node allows all node command line arguments as well as ts-node's own. Would be wonderful if jasmine-ts could do the same (i.e. allow jasmine arguments + ts-node arguments + node arguments).

**Comment by lonix1** [comment]
Also `--project` option so we can specify the `tsconfig.json` file.

**Comment by ert78gb** [comment]
I think the 0.3.2 version support your requirements. If not please feel free to reopen the issue
