### ISSUE TITLE
Add support for debugging through ts-node

### ISSUE THREAD

**Issue by benjcallaghan** [svi3c/jasmine-ts#16]
ts-node offers the --inspect flag that allows debugging. Our project relies on that flag to use the debugger in VS Code. We're having some issues with our unit tests, but we can't find anyway to attach a debugger to jasmine-ts. Please add support for the --inspect flag that is built-in to ts-node so we can use a proper debugger.

**Comment by dougajmcdonald** [comment]
I would certainly like a way to debug tests also via VSCode, so would fully support this idea

**Comment by kohashi** [comment]
In my environment, I can use debugger in VS code.
Set launch.json like this
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "jasmine-test ",
            "program": "${workspaceFolder}/node_modules/jasmine-ts/lib/index.js",
            "args": [
              "./src/**/*.spec.ts",
            ],
            "cwd": "${workspaceRoot}"
        }
    ]
}
```

It is possible to use variable-inspector, watch, callstack and breakpoint.

**Comment by benjcallaghan** [comment]
@kohashi I tried the configuration you posted. It successfully ran my test, but I didn't have any of the debugging features of VS Code. If I hover over a (disabled) breakpoint, it says "Breakpoint ignored because generated code not found (source map problem)?". Any suggestions?

**Comment by kohashi** [comment]
@benjcallaghan 

You should set inlineSources in tsconfig.json

```
{
  "compilerOptions": { 
     ...,
     "inlineSources": true
}
```

And now my launch.json was updated.

```
{
    "version": "0.2.0",
    "configurations": [
        {
          "type": "node",
          "request": "launch",
          "name": "Jasmine-ts Tests",
          "program": "${workspaceFolder}/node_modules/jasmine-ts/lib/index.js",
          "args": [
            "./src/**/*.spec.ts",
          ],
          "stopOnEntry": false,
          "cwd": "${workspaceRoot}",
          "protocol": "inspector",
          "outputCapture":"std"
    }
    ]
}

```

.

**Comment by benjcallaghan** [comment]
@kohashi Thank you. That configuration works for me. I can now debug my tests through VS Code with all its power. The terminal output is less than what I would normally get from the command line, but it's definitely a step in the right direction.
