### ISSUE TITLE
Example for helper files

### ISSUE THREAD

**Issue by monkpit** [svi3c/jasmine-ts#18]
I am loving this project, but I can't seem to get Jasmine helpers working. I've tried using TS and JS files for my helpers, I've tried specifying their location using the `--helper` flag on the command line and also by editing jasmine.json, and I can't seem to get anything to work.

Could someone provide an example of working helper files using jasmine-ts? Something simple, just like a `beforeEach` or `beforeAll` writing to `console.log`?

**Comment by ert78gb** [comment]
the `--helper` argument supported from the 0.3.2 version
