### ISSUE TITLE
Any TS_NODE_OPTIONS passed for ts-node get passed to jasmine and cause errors

### ISSUE THREAD

**Issue by kbirger** [svi3c/jasmine-ts#19]
Steps:
1. create tsconfig.json in a subdirectory of your code
2.  jasmine-ts --project temp/tsconfig.json "src/**/*.spec.ts"

> Unknown options: --project

>Usage: jasmine [command] [options] [files]

Because the last line of code which executes jasmine sends process.argv.slice(2), all of the arguments that ts-node knows which jasmine does not know get passed on.

**Comment by Syltty** [comment]
Hi, I have the same problem, any workaround? Thank you.

**Comment by vreality64** [comment]
I think it's matter of command initiator.

```ts
command.run(jasmine, process.argv.slice(2));
```

`process.argv.slice(2)` will returns arguments list having `--project`, `temp/tsconfig.json`. Both arguments are recognized as jasmine [options], but it's not right option.

My suggestions is distinguish `jasmine` and `ts-node` options. It's more clear than now.
- `jasmine.json` for `jasmine` options 
- other arguments for `ts-node` options

**Comment by rupamroy** [comment]
Is there an ETA for this to be fixed? Or this there any workaround for this
