### ISSUE TITLE
SyntaxError: Unexpected token [initReporters = ()]

### ISSUE THREAD

**Issue by Izhaki** [svi3c/jasmine-ts#2]
With the following package.json

    {
      "name": "jasmine-ts-sample-project",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "provision": "typings install",
        "test": "jasmine-ts '*.spec.ts'"
      },
      "author": "",
      "license": "ISC",
      "devDependencies": {
        "jasmine-ts": "0.0.2"
      }
    }

either running the tests or calling ` node_modules/.bin/jasmine-ts init` fires the following error:

    var initReporters = () => {
                         ^
    SyntaxError: Unexpected token )
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3

**Comment by svi3c** [comment]
The code is actually written in ES2015. So you need at least node v4.0.0, I suppose.

**Comment by Izhaki** [comment]
I'm pretty sure I've tried this with node v5.x and got the same message. Also tried ts-node and didn't work.

**Comment by svi3c** [comment]
Sorry, but I cannot reproduce this. Just checked with node v4.0.0 and v5.0.0 and it just works.
But I'm pretty sure that this error is caused because of a lack of Arrow-Function support in your VM.
I just tried it with node v0.12.15 and it breaks with the same error you are mentioning.
