### ISSUE TITLE
Jasmine should be a peer dependency

### ISSUE THREAD

**Issue by kbirger** [svi3c/jasmine-ts#27]
I just realized that this package uses its own version of Jasmine. This is a problem for multiple reasons:

1. It means I now have 2 versions of jasmine in my package
2. This package needs to be updated for every minor update to jasmine

Please switch Jasmine to a peer dependency and just lock the range to a major version so that consumers can use their own jasmine.

**Comment by bennyn** [comment]
I would also like to use `jasmine-ts` with Jasmine 3 but it ships with Jasmine 2. 😢
