### ISSUE TITLE
Looking for new project owner

### ISSUE THREAD

**Issue by svi3c** [svi3c/jasmine-ts#30]
Hi,

I'm sorry that I'm not actively maintaining this repo for some time now.
The reason is that I'm currently working with jest and I have no time left time to work on this project.

So if anyone is interested in taking over this project, feel free to contact me.

**Comment by kbirger** [comment]
Hi @svi3c 

Thanks, I'm sure I'm not the only one who appreciates this project and your time.
I could give it a shot. I did notice there were a handful of other maintainers currently. Is everyone else off this project as well?

**Comment by moneal** [comment]
I think this is a great project and would love to help with what I can.

**Comment by svi3c** [comment]
Hi @kbirger and @moneal,

sorry for the late response. Thanks for the interests. I added you as collaborators.

**Comment by svi3c** [comment]
I'll close this ticket for now. Maybe having some help here is sufficient.

**Comment by kbirger** [comment]
Hi @svi3c - I don't think you actually added either of us. At least I don't see us on the list:
https://github.com/svi3c/jasmine-ts/graphs/contributors

**Comment by kbirger** [comment]
Hi @svi3c - I don't think you actually added either of us. At least I don't see us on the list:
https://github.com/svi3c/jasmine-ts/graphs/contributors

**Comment by JanCVanB** [comment]
@svi3c It looks like @ert78gb is actively maintaining a good fork! Can you add them as a contributor or update this repo/package to redirect to theirs?
