### ISSUE TITLE
Problem with last update

### ISSUE THREAD

**Issue by oscarcalvo** [svi3c/jasmine-ts#31]
Hi, I have my code running well with previous version of jasmine-ts, but if I update to 0.3.0 and run tests it says always "No specs found"
The line is: jasmine-ts  ./server/tsconfig.json \"./server/spec/**/*.spec.ts\"

any tip? I guess can be anything with paths, how can I check full path where it is looking for spec files?

Thanks

**Comment by clickthisnick** [comment]
@oscarcalvo Seems to be related to this https://github.com/svi3c/jasmine-ts/commit/6c06d317fff7528c16f80860f2db6bd5693bed34#diff-f41e9d04a45c83f3b6f6e630f10117feR63

Looks like after the update to jasmine-ts 0.3.0 there's two things needed.
1.) Need to install `ts-node`
2.) All arguments passed to `jasmine-ts` need to have one of these in that argument `argv.config || process.env.JASMINE_CONFIG_PATH || "spec/support/jasmine.json";`

Here's an example of how I fixed my tests after upgrading:
https://github.com/clickthisnick/dynamic-release-checklist/pull/7/commits/41928bdd3a90f0513b1c756030b6803e612357da

**Comment by oscarcalvo** [comment]
Thanks, it works now

I changed 
jasmine-ts ./server/tsconfig.json "./server/spec/**/*.spec.ts"
for
jasmine-ts  ./server/tsconfig.json  --config=./server/spec/support/jasmine.json

And added jasmine.json

{
  "spec_dir": "server/spec",
  "spec_files": [
    "**/**.spec.ts"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
