### ISSUE TITLE
After upgrade, one spec.ts file cannot be tested

### ISSUE THREAD

**Issue by isaacfi** [svi3c/jasmine-ts#33]
I need to run one test file, but it cannot be passed as argument. After last upgrade this is forced to run the spec.ts files according to the jasmin.json configuration file.

What I'm trying to do:

`./node_modules/.bin/jasmine-ts ./test/business/user.spec.ts`

but it gives me:
**No specs found**

So, if I try to pass the config file:

`./node_modules/.bin/jasmine-ts --config=jasmine.json ./test/business/user.spec.ts`

where the jasmine.json content is:

```
{
  "spec_dir": "test",
  "spec_files": ["**/*spec.ts"],
  "random": false,
  "reporters": [
    {
      "name": "jasmine-spec-reporter#SpecReporter",
      "options": {
        "displayStacktrace": "all"
      }
    }
  ]
}
```

it runs all the spec.ts files inside the test/business folder.

Please add one file support if the configuration file is not passed to the jasmine-ts command.

Regards

**Comment by gkalpak** [comment]
FWIW, this was broken in #25. It definitely seems unintentional, since now the recommended way in `README.md` doesn't work any more: `jasmine-ts "path/to/specs/**/*.spec.ts"` 😞

(For anyone looking for a workign version, this seems to have been broken in v0.3.0. v0.2.1 works fine.)

**Comment by c00** [comment]
I got stuck on this issue as well. For me the workaround was to bypass jasmine-ts altogether. I think a working solution is described in #34 , but until that's merged, the below workaround works.

From the command line Instead of running `jasmine-ts some/file.spec.ts`, what works is `ts-node jasmine some/file.spec.ts`. In case you're trying to use vscode debugger, the following `launch.json` will help you out:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Jasmine Current File",
      "program": "${workspaceFolder}/node_modules/.bin/ts-node", //refer to ts-node here
      "args": [
        "node_modules/.bin/jasmine", //and call jasmine here.
        "${file}",
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
  ]
}
```
