### ISSUE TITLE
suggestion: one simple example

### ISSUE THREAD

**Issue by guenam** [svi3c/jasmine-ts#4]
I'm new to unit testing and wasn't successful setting up the proper conf to make it work. For some reason, probably something obvious that I can't see, when I run 'npm test', I get '... Started. No Spec found'.

So, *ideally*, a super simple working example would be provided for noobs like me. I understand this is some tedious extra work for an experimented dev, so just a suggestion, not a request.

**Comment by guenam** [comment]
OK, I got it to work finally. I'll describe what I had to do, in case it helps somehow:

NB : I work on Windows so I have to replace / by \\ in paths.

1. **in package.json, removed the '' around the spec path**, so that the script command is "test": "jasmine-ts spec\\**\\*.spec.ts" and not "test": "jasmine-ts **'**spec\\**\\*.spec.ts**'**"
=> I guess this is a newbie mistake

However, the result was better but not ideal : 
> Started
> .
> 1 spec, 0 failures

=> no description of what test had been done. 

2. **enable jasmine-spec-reporter**: e.g. npm install it and inserting the provided conf lines in jasmine.json

Then the result of npm test was clean:

> Spec started
>   test if true is true
>     √ should work

**Comment by svi3c** [comment]
Hi @guenam,

thanks for sharing this. I'll rework the readme and try to make it more clear.

Which OS are you running on?
AFAIK the single quotes are causing issues on windows systems. If you leave out the quotes, your shell has to be able to resolve the wildcard. With quotes the pattern is not interpreted by your shell, but by the program.

Maybe escaped double quotes work better for you:

```
"test": "jasmine-ts \"spec/**/.spec.ts\""
```

**Comment by guenam** [comment]
Hi! 

Yes indeed, I'm on Windows 10. I just tried the escaped double quotes, it works perfectly. 

It also appears that typing jasmine-ts spec\**\*.spec.ts directly into powershell or cmd works as well. It doesn't if using the Git bash, as expected.

So yes, escaped double quotes is the way to go. 

Thanks for your quick and kind reply.
