### ISSUE TITLE
Pass parameters to jasmine?

### ISSUE THREAD

**Issue by richbern** [svi3c/jasmine-ts#40]
I've got a project using jasmine-ts to run unit tests for me. We've configured our jasmine.json file to set "random" to "true" so tests are run with a random seed. This can help find unit test errors when bad assumptions are made.

However, when we get a failing test, I can't find a way to get that seed to be used by Jasmine again. I've attempted setting the seed property in the jasmine.json file; I've tried using a command line parameter; both are ignored. I've resorted to modifying jasmine's js code to use a static seed to run tests, but that seems less than ideal.

I'm not sure if anyone's actively looking at this or not, but thought I'd post the issue in case someone has ideas on how to get the seed passed through.

**Comment by ert78gb** [comment]
The 0.3.2 version support the full jasmine CLI arguments
