### ISSUE TITLE
Peer dependency warning in latest jasmine-ts

### ISSUE THREAD

**Issue by crfrolik** [svi3c/jasmine-ts#41]
```
warning " > jasmine-ts@0.3.0" has incorrect peer dependency "ts-node@>=3.2.0 <8".
```
If jasmine-ts supports ts-node 8 (see #32), then the peer dependency field in `package.json` should also be updated.

**Comment by crfrolik** [comment]
It looks like the peer dependency has been updated.
Someone just needs to make a new release of jasmine-ts.

**Comment by estoel81** [comment]
@svi3c Is it possible to merge the PR to update peer dependencies?
 
`found 2 low severity vulnerabilities in 573 scanned packages`

**Comment by ert78gb** [comment]
The 0.3.2 version contains the fix
