### ISSUE TITLE
Suggestion: add cli option to configure tsconfig file.

### ISSUE THREAD

**Issue by 0x4d464d48** [svi3c/jasmine-ts#5]
I'm using this tool for a project with several tsconfig files and I was wondering if there's going to be an option inserted to provide the path to tsconfig file before running the jasmine tests. I can run the tsconfig file I want by copying a tsconfig file into the same directory as the `jasmine.json` file or by changing the value of the `TS_NODE_PROJECT` environment variable. 

It would be better for my work flow if I could just call the `jasmine-ts` with a param like `--tsconfig path/to/tsconfig.json`. Is this in the works?

**Comment by svi3c** [comment]
Hi,

looks like a good idea to me. We could parse the command line params, grab the subset of the [ts-node options](https://www.npmjs.com/package/ts-node#configuration-options) and pass it through to ts-node.register(). The ts-node options seem not to conflict with the jasmine options, so this should not lead to problems.
The easiest way to achieve this would be [yargs](https://www.npmjs.com/package/yargs), I guess.

**Comment by adrian-moisa** [comment]
I'm not sure how this works, can you provide a sample of the command? Thanks!
