### ISSUE TITLE
This repo is dead, use Róbert's instead! :)

### ISSUE THREAD

**Issue by JanCVanB** [svi3c/jasmine-ts#50]
`npm i -D @ert78gb/jasmine-ts`
https://github.com/ert78gb/jasmine-ts
https://www.npmjs.com/package/@ert78gb/jasmine-ts

Thank you, @ert78gb!

**Comment by ert78gb** [comment]
I got a maintainer invite from @svi3c and I accepted it. I will update this repo if I will got access to the npmjs.com too, because I won't wanna wait weeks until a package will be published.

**Comment by svi3c** [comment]
Hey @ert78gb,
I just gave you the rights for the npm package.
Thanks for your support! 👍 
My apologies for being inactive in this project for so long!
I have no stakes in this project anymore, since I settled with jest in all my active projects.

**Comment by ert78gb** [comment]
Hi @svi3c I updated the repo and published a new version, but I don't have full access to the repo - e.g. I can't set secrets and branch protection, - it is the limitation of the GitHub personal repo contributor setup.

Do you have any idea how can we handle it?
My ideas:
1) move the repo to the `jasmine` org. Someine has to talk with them about it.
2) create a standalone org and transfer the repo under that org.

**Comment by ert78gb** [comment]
I archived my fork and maintain it so I close this issue
