### ISSUE TITLE
--project option fails.

### ISSUE THREAD

**Issue by sokudo** [svi3c/jasmine-ts#60]
Using --project option correctly passes a project value to ts-node.
But then the same project value is passed as a spec name to jasmine.

argv entries consumed by ts-node and node CLI options should be removed from argv before processing commandOptions for jasmine.

**Comment by ert78gb** [comment]
I will fix it this week.

**Comment by ert78gb** [comment]
@sokudo please check the 0.3.3 version.

**Comment by ert78gb** [comment]
I close it because lack of answer
