### ISSUE TITLE
Code Coverage with istanbul

### ISSUE THREAD

**Issue by antoniusostermann** [svi3c/jasmine-ts#7]
Hey!

Do you have any good idea how to combine jasmine-ts with istanbul for code coverage?

I already tried sth. like ``istanbul cover --include-all-sources jasmine-ts spec/**/*.spec.ts``.

Any help would be appreciated!

**Comment by svi3c** [comment]
Hi @antoniusostermann,

sorry for the delay.
At the moment I'm quite busy and I did not get in touch with istanbul yet. Not sure when I'll get to this.
If you like to share any progress, feel free to raise a PR.

**Comment by iwllyu** [comment]
@antoniusostermann are you tied to istanbul? We use nyc (frankly I don't really know the difference between the two [but the owner mentions it here](https://github.com/istanbuljs/nyc/issues/524#issuecomment-280979372)) 

we use nyc like so (from package.json) `"test": "nyc jasmine-ts ./src/**/*.spec.[tj]s",`

**Comment by antoniusostermann** [comment]
Thanks for the hint! With using the `include` option, I now get an output, but the covered lines are not calculated correctly. Nyc tells me all covered lines are always at 0%, although I have files with `funcs` and `branch` covered at 100%. 

Currently I have this filestructure:
`/src` - my typescript files
`/lib` - the resulting javascript
`/spec` - the specs

The javascript in `lib` is created by gulp and included with the `include` option. But how does jasmine-ts know that it should use this javascript? Or does it compile the typescript source files needed for testing on its own? In that case, I would need to specify a specific `include` directory fitting to `ts-node`'s compilation process, don't I?

**Comment by iwllyu** [comment]
afaik jasmine-ts compiles and runs the ts on it's own using node-ts. I don't have any generated js files before during or after running jasmine-ts

**Comment by svi3c** [comment]
@iwllyu Right, jasmine-ts just uses ts-node to directly transpile and execute the ts files.
@antoniusostermann This npm script works like a charm for me:
```
"test": "nyc -e .ts -x \"*.spec.ts\" jasmine-ts \"**/*.spec.ts\""
```

**Comment by antoniusostermann** [comment]
@svi3c Thanks so much!
