### ISSUE TITLE
typescript 2.4.1 cannot resolve modules

### ISSUE THREAD

**Issue by iwllyu** [svi3c/jasmine-ts#8]
with typescript 2.4.1 there was a breaking change to ts-node. ts-node now fails to find any @types navigation files

https://github.com/Microsoft/TypeScript/issues/16772#issuecomment-311579855

this is fixed in ts-node v3.1.0

I'm not sure how feasible this is but I know serverless-webpack made webpack a peer dependency, making it so the user can use an arbitrary version of webpack with serverless-webpack. Can we do something similar with jasmine-ts?

**Comment by iwllyu** [comment]
or we could just bump the ts-node version

**Comment by antoniusostermann** [comment]
+1
